version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_DB: inGameTestDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - programs

  program:
    container_name: program
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - programs

  pgweb:
    image: 'sosedoff/pgweb'
    restart: always
    ports:
      - '8081:8081'
    environment:
      - PGWEB_DATABASE_URL=postgres://user:password@postgres:5432/inGameTestDb?sslmode=disable
    networks:
      - programs
networks:
  programs:
